include ../env.$(ENVIRONMENT).mk
include ../common.mk

.PHONY: deploy
deploy:
	@echo ""
	@echo ""
	@echo "This is Disabled since it does not work with Nginx"
	#@kubecfg update $(ENVIRONMENT).jsonnet
	#@kubectl rollout status -n opa-ext-auth deployment opa
