replicaCount: 2
backend: "http://backend-podinfo:9898/echo"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    'nginx.ingress.kubernetes.io/auth-url': "http://opa.opa-ext-auth.svc.cluster.local.:8181"
    'nginx.ingress.kubernetes.io/auth-keepalive': "3"
    #'nginx.ingress.kubernetes.io/auth-method': 'POST'
    #'nginx.ingress.kubernetes.io/PATH ???? 
